# curl -X POST
#  http://localhost:8080/announces
#  -H 'Content-Type: multipart/form-data'
#  -F 'file=@/path/to/file.txt'
#  -F 'announceDTOJson={"ancTitle":"제목","ancContent":"내용","ancDate":"2020-11-11","ancWriter":"김고무","hits":0}'
POST http://localhost:8080/announces
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="file.txt"

< C:\Users\hi\Desktop\file\jjang.png
--WebAppBoundary
Content-Disposition: form-data; name="announceDTO"

{
"ancTitle":"제발",
"ancContent":"낫 널 테스트",
"ancDate":"1997-19-20",
"ancWriter":"김낫널",
"hits":999
}
--WebAppBoundary--

### 공지사항만 등록
POST http://localhost:8080/announces
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="announceDTO"

{
"ancTitle":"null",
"ancContent":"null test",
"ancDate":"1997-19-97",
"ancWriter":"김널판지",
"hits":1
}
--WebAppBoundary--

### 공지사항 전체조회 페이징
GET http://localhost:8080/announces?page=2

### 공지사항 상세 조회
GET http://localhost:8080/announces/34

### 공지사항 수정
PUT http://localhost:8080/announces/6
Content-Type: application/json

{
  "ancTitle" : "",
  "ancContent" : ""
}

### 공지사항 삭제
DELETE http://localhost:8080/announces/3