### 휴가 신청 내역 조회 - 구성원
GET http://localhost:8080
Authorization: BEARER eyJkYXRlIjoxNzE0NTIyNDEyOTQyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJSb2xlIjoiQURNSU4iLCJpbWFnZSI6IuydtOuvuOyngOqwgCDrk6TslrTqsIgg6rK966GcIiwic3ViIjoiaW5zaWRlcidzIHRva2VuOiAyNDA0MDEwMDEiLCJ1c2VyTmFtZSI6Iuq5gOyngO2ZmCIsImV4cCI6MTcxNDYwODgxMiwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA0MDEwMDF9.Ajn8VLUnWGkJJEOxi9o6ykMD5P6_IGK3wKKJcptuOrU

### 휴가 신청 내역 조회 - 관리자
GET http://localhost:8080
Authorization: BEARER eyJkYXRlIjoxNzE0NTIyNDEyOTQyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJSb2xlIjoiQURNSU4iLCJpbWFnZSI6IuydtOuvuOyngOqwgCDrk6TslrTqsIgg6rK966GcIiwic3ViIjoiaW5zaWRlcidzIHRva2VuOiAyNDA0MDEwMDEiLCJ1c2VyTmFtZSI6Iuq5gOyngO2ZmCIsImV4cCI6MTcxNDYwODgxMiwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA0MDEwMDF9.Ajn8VLUnWGkJJEOxi9o6ykMD5P6_IGK3wKKJcptuOrU

### 휴가 신청
POST http://localhost:8080
Authorization: BEARER eyJkYXRlIjoxNzE0NTIyNDEyOTQyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJSb2xlIjoiQURNSU4iLCJpbWFnZSI6IuydtOuvuOyngOqwgCDrk6TslrTqsIgg6rK966GcIiwic3ViIjoiaW5zaWRlcidzIHRva2VuOiAyNDA0MDEwMDEiLCJ1c2VyTmFtZSI6Iuq5gOyngO2ZmCIsImV4cCI6MTcxNDYwODgxMiwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA0MDEwMDF9.Ajn8VLUnWGkJJEOxi9o6ykMD5P6_IGK3wKKJcptuOrU

### 휴가 신청 취소 (삭제)
DELETE http://localhost:8080
Authorization: BEARER eyJkYXRlIjoxNzE0NTIyNDEyOTQyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJSb2xlIjoiQURNSU4iLCJpbWFnZSI6IuydtOuvuOyngOqwgCDrk6TslrTqsIgg6rK966GcIiwic3ViIjoiaW5zaWRlcidzIHRva2VuOiAyNDA0MDEwMDEiLCJ1c2VyTmFtZSI6Iuq5gOyngO2ZmCIsImV4cCI6MTcxNDYwODgxMiwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA0MDEwMDF9.Ajn8VLUnWGkJJEOxi9o6ykMD5P6_IGK3wKKJcptuOrU

### 휴가 취소 요청
POST http://localhost:8080
Authorization: BEARER eyJkYXRlIjoxNzE0NTIyNDEyOTQyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJSb2xlIjoiQURNSU4iLCJpbWFnZSI6IuydtOuvuOyngOqwgCDrk6TslrTqsIgg6rK966GcIiwic3ViIjoiaW5zaWRlcidzIHRva2VuOiAyNDA0MDEwMDEiLCJ1c2VyTmFtZSI6Iuq5gOyngO2ZmCIsImV4cCI6MTcxNDYwODgxMiwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA0MDEwMDF9.Ajn8VLUnWGkJJEOxi9o6ykMD5P6_IGK3wKKJcptuOrU

### 발생 내역 조회
GET http://localhost:8080
Authorization: BEARER eyJkYXRlIjoxNzE0NTIyNDEyOTQyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJSb2xlIjoiQURNSU4iLCJpbWFnZSI6IuydtOuvuOyngOqwgCDrk6TslrTqsIgg6rK966GcIiwic3ViIjoiaW5zaWRlcidzIHRva2VuOiAyNDA0MDEwMDEiLCJ1c2VyTmFtZSI6Iuq5gOyngO2ZmCIsImV4cCI6MTcxNDYwODgxMiwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA0MDEwMDF9.Ajn8VLUnWGkJJEOxi9o6ykMD5P6_IGK3wKKJcptuOrU

### 휴가 발생
POST http://localhost:8080
Authorization: BEARER eyJkYXRlIjoxNzE0NTIyNDEyOTQyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJSb2xlIjoiQURNSU4iLCJpbWFnZSI6IuydtOuvuOyngOqwgCDrk6TslrTqsIgg6rK966GcIiwic3ViIjoiaW5zaWRlcidzIHRva2VuOiAyNDA0MDEwMDEiLCJ1c2VyTmFtZSI6Iuq5gOyngO2ZmCIsImV4cCI6MTcxNDYwODgxMiwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA0MDEwMDF9.Ajn8VLUnWGkJJEOxi9o6ykMD5P6_IGK3wKKJcptuOrU

### 상세 조회
GET http://localhost:8080
Authorization: BEARER eyJkYXRlIjoxNzE0NTIyNDEyOTQyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJSb2xlIjoiQURNSU4iLCJpbWFnZSI6IuydtOuvuOyngOqwgCDrk6TslrTqsIgg6rK966GcIiwic3ViIjoiaW5zaWRlcidzIHRva2VuOiAyNDA0MDEwMDEiLCJ1c2VyTmFtZSI6Iuq5gOyngO2ZmCIsImV4cCI6MTcxNDYwODgxMiwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA0MDEwMDF9.Ajn8VLUnWGkJJEOxi9o6ykMD5P6_IGK3wKKJcptuOrU

### 휴가 신청 처리
PUT http://localhost:8080
Authorization: BEARER eyJkYXRlIjoxNzE0NTIyNDEyOTQyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJSb2xlIjoiQURNSU4iLCJpbWFnZSI6IuydtOuvuOyngOqwgCDrk6TslrTqsIgg6rK966GcIiwic3ViIjoiaW5zaWRlcidzIHRva2VuOiAyNDA0MDEwMDEiLCJ1c2VyTmFtZSI6Iuq5gOyngO2ZmCIsImV4cCI6MTcxNDYwODgxMiwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA0MDEwMDF9.Ajn8VLUnWGkJJEOxi9o6ykMD5P6_IGK3wKKJcptuOrU
