### 받은 쪽지 목록 전체 조회
GET http://localhost:8080/members/240501107/notes?receiverId=240501107&sort=noteNo&receiveDeleteYn=N&sendDeleteYn=N
Authorization: BEARER eyJkYXRlIjoxNzE1NTIzNTE3OTQxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA1MDExMDciLCJkZXBhcnRObyI6MSwicm9sZSI6IkFETUlOIiwiaW1hZ2VVcmwiOiLsnbTrr7jsp4Ag6rK966Gc65Ok7Ja06rCIIOqzsyEhISEhISIsIm5hbWUiOiLrsJXqs7HssL0iLCJtZW1iZXJTdGF0dXMiOiLsnqzsp4EiLCJleHAiOjE3MTU2MDk5MTcsImRlcGFydE5hbWUiOiLsnbjsgqztjIAiLCJtZW1iZXJJZCI6MjQwNTAxMTA3fQ.bix4SCbNQlp1NfjsuFod_Yx__TVS05tk9HCTjg-af08

### 보낸 쪽지 목록 전체 조회
GET http://localhost:8080/members/240501107/notes?senderId=240501107&sort=noteNo&sendDeleteYn=N&receiveDeleteYn=N
Authorization: BEARER eyJkYXRlIjoxNzE1NTIzNTE3OTQxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA1MDExMDciLCJkZXBhcnRObyI6MSwicm9sZSI6IkFETUlOIiwiaW1hZ2VVcmwiOiLsnbTrr7jsp4Ag6rK966Gc65Ok7Ja06rCIIOqzsyEhISEhISIsIm5hbWUiOiLrsJXqs7HssL0iLCJtZW1iZXJTdGF0dXMiOiLsnqzsp4EiLCJleHAiOjE3MTU2MDk5MTcsImRlcGFydE5hbWUiOiLsnbjsgqztjIAiLCJtZW1iZXJJZCI6MjQwNTAxMTA3fQ.bix4SCbNQlp1NfjsuFod_Yx__TVS05tk9HCTjg-af08

### 쪽지 상세 조회
GET http://localhost:8080/notes/1
Authorization: BEARER eyJkYXRlIjoxNzE1NTIzNTE3OTQxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA1MDExMDciLCJkZXBhcnRObyI6MSwicm9sZSI6IkFETUlOIiwiaW1hZ2VVcmwiOiLsnbTrr7jsp4Ag6rK966Gc65Ok7Ja06rCIIOqzsyEhISEhISIsIm5hbWUiOiLrsJXqs7HssL0iLCJtZW1iZXJTdGF0dXMiOiLsnqzsp4EiLCJleHAiOjE3MTU2MDk5MTcsImRlcGFydE5hbWUiOiLsnbjsgqztjIAiLCJtZW1iZXJJZCI6MjQwNTAxMTA3fQ.bix4SCbNQlp1NfjsuFod_Yx__TVS05tk9HCTjg-af08

### 쪽지 발송
POST http://localhost:8080/notes
Content-Type: application/json
Authorization: BEARER eyJkYXRlIjoxNzE1NTIzNTE3OTQxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA1MDExMDciLCJkZXBhcnRObyI6MSwicm9sZSI6IkFETUlOIiwiaW1hZ2VVcmwiOiLsnbTrr7jsp4Ag6rK966Gc65Ok7Ja06rCIIOqzsyEhISEhISIsIm5hbWUiOiLrsJXqs7HssL0iLCJtZW1iZXJTdGF0dXMiOiLsnqzsp4EiLCJleHAiOjE3MTU2MDk5MTcsImRlcGFydE5hbWUiOiLsnbjsgqztjIAiLCJtZW1iZXJJZCI6MjQwNTAxMTA3fQ.bix4SCbNQlp1NfjsuFod_Yx__TVS05tk9HCTjg-af08

{
  "noteTitle": "ㅎㅇ 곱창아?",
  "noteContent": "곱창이 ㅎㅇ",
  "senderId": 240501852,
  "receiverId": 240501107
}

### 쪽지 삭제
PUT http://localhost:8080/notes/9
Content-Type: application/json
Authorization: BEARER eyJkYXRlIjoxNzE1NDM2Mjc4ODc4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA1MDE1MjkiLCJkZXBhcnRObyI6MSwicm9sZSI6IkFETUlOIiwiaW1hZ2VVcmwiOiIxMjM0NSIsIm5hbWUiOiLrp4zrkZAiLCJtZW1iZXJTdGF0dXMiOiLsnqzsp4EiLCJleHAiOjE3MTU1MjI2NzgsImRlcGFydE5hbWUiOiLsnbjsgqztjIAiLCJtZW1iZXJJZCI6MjQwNTAxNTI5fQ.elypjbgDBq8kc9wZCy2Sj3-K7PAFzOAqM9HCxePHEg8

{
  "sendDeleteYn": "Y"
}

###
GET ws:/localhost:8080/wss/chatting
Authorization: BEARER eyJkYXRlIjoxNzE1MDYyODMyNjYxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA1MDExMzkiLCJyb2xlIjoiQURNSU4iLCJpbWFnZVVybCI6IuydtOuvuOyngCDqsr3roZzrk6TslrTqsIgg6rOzISEhISEhIiwibmFtZSI6Iuq5gOyngO2ZmOydtOydtOydtOydtOydtOydtOOFoyIsIm1lbWJlclN0YXR1cyI6IuyerOyngSIsImV4cCI6MTcxNTE0OTIzMiwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA1MDExMzl9.zPtT5ukG3SYmqUVKfAwPVnn7kO3yiMdpc1ns6QSCj-s
