### 받은 쪽지 목록 전체 조회
GET http://localhost:8080/members/240401001/notes?receiverId=240401001&sort=noteNo&deleteYn=N
Authorization: BEARER eyJkYXRlIjoxNzE0NzMwOTA3MTE4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA1MDE5NTkiLCJyb2xlIjoiQURNSU4iLCJpbWFnZVVybCI6IuydtOuvuOyngCDqsr3roZzrk6TslrTqsIgg6rOzISEhISEhIiwibmFtZSI6Iuq5gOyngO2ZmOydtOydtOydtOydtOydtOydtOOFoyIsIm1lbWJlclN0YXR1cyI6IuyerOyngSIsImV4cCI6MTcxNDgxNzMwNywiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA1MDE5NTl9._CWr_FrrRAlR2CeTCzrCG0Vlty1Hw82sVrm8sb0rr08

### 보낸 쪽지 목록 전체 조회
GET http://localhost:8080/members/240401001/notes?senderId=240401001&sort=noteNo&deleteYn=N
Authorization: BEARER eyJkYXRlIjoxNzE0NzMwOTA3MTE4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA1MDE5NTkiLCJyb2xlIjoiQURNSU4iLCJpbWFnZVVybCI6IuydtOuvuOyngCDqsr3roZzrk6TslrTqsIgg6rOzISEhISEhIiwibmFtZSI6Iuq5gOyngO2ZmOydtOydtOydtOydtOydtOydtOOFoyIsIm1lbWJlclN0YXR1cyI6IuyerOyngSIsImV4cCI6MTcxNDgxNzMwNywiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA1MDE5NTl9._CWr_FrrRAlR2CeTCzrCG0Vlty1Hw82sVrm8sb0rr08

### 쪽지 상세 조회
GET http://localhost:8080/notes/1
Authorization: BEARER eyJkYXRlIjoxNzE0NzMwOTA3MTE4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA1MDE5NTkiLCJyb2xlIjoiQURNSU4iLCJpbWFnZVVybCI6IuydtOuvuOyngCDqsr3roZzrk6TslrTqsIgg6rOzISEhISEhIiwibmFtZSI6Iuq5gOyngO2ZmOydtOydtOydtOydtOydtOydtOOFoyIsIm1lbWJlclN0YXR1cyI6IuyerOyngSIsImV4cCI6MTcxNDgxNzMwNywiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA1MDE5NTl9._CWr_FrrRAlR2CeTCzrCG0Vlty1Hw82sVrm8sb0rr08

### 쪽지 발송
POST http://localhost:8080/notes
Content-Type: application/json
Authorization: BEARER eyJkYXRlIjoxNzE0NzMwOTA3MTE4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA1MDE5NTkiLCJyb2xlIjoiQURNSU4iLCJpbWFnZVVybCI6IuydtOuvuOyngCDqsr3roZzrk6TslrTqsIgg6rOzISEhISEhIiwibmFtZSI6Iuq5gOyngO2ZmOydtOydtOydtOydtOydtOydtOOFoyIsIm1lbWJlclN0YXR1cyI6IuyerOyngSIsImV4cCI6MTcxNDgxNzMwNywiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA1MDE5NTl9._CWr_FrrRAlR2CeTCzrCG0Vlty1Hw82sVrm8sb0rr08

{
  "noteTitle": "TEST 1",
  "noteContent": "CONTENT 1",
  "senderId": 240401001,
  "receiverId": 12345
}

### 쪽지 삭제
PUT http://localhost:8080/notes/3
Content-Type: application/json
Authorization: BEARER eyJkYXRlIjoxNzE0NzMwOTA3MTE4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA1MDE5NTkiLCJyb2xlIjoiQURNSU4iLCJpbWFnZVVybCI6IuydtOuvuOyngCDqsr3roZzrk6TslrTqsIgg6rOzISEhISEhIiwibmFtZSI6Iuq5gOyngO2ZmOydtOydtOydtOydtOydtOydtOOFoyIsIm1lbWJlclN0YXR1cyI6IuyerOyngSIsImV4cCI6MTcxNDgxNzMwNywiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA1MDE5NTl9._CWr_FrrRAlR2CeTCzrCG0Vlty1Hw82sVrm8sb0rr08

{
  "deleteYn": "Y"
}

###
GET ws:/localhost:8080/wss/chatting
Authorization: BEARER eyJkYXRlIjoxNzE0NzMwOTA3MTE4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA1MDE5NTkiLCJyb2xlIjoiQURNSU4iLCJpbWFnZVVybCI6IuydtOuvuOyngCDqsr3roZzrk6TslrTqsIgg6rOzISEhISEhIiwibmFtZSI6Iuq5gOyngO2ZmOydtOydtOydtOydtOydtOydtOOFoyIsIm1lbWJlclN0YXR1cyI6IuyerOyngSIsImV4cCI6MTcxNDgxNzMwNywiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA1MDE5NTl9._CWr_FrrRAlR2CeTCzrCG0Vlty1Hw82sVrm8sb0rr08
