### 수요조사 목록 전체 조회
GET http://localhost:8080/surveys?page=0&properties=leaveSubNo&direction=DESC
Authorization: BEARER eyJkYXRlIjoxNzE1MTY1NzY0ODQ5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA0MDE4MzUiLCJyb2xlIjoiQURNSU4iLCJpbWFnZVVybCI6IjEiLCJuYW1lIjoi6rmA7KeA7ZmYIiwibWVtYmVyU3RhdHVzIjoi7J6s7KeBIiwiZXhwIjoxNzE1MjUyMTY0LCJkZXBhcnROYW1lIjoi7J247IKs7YyAIiwibWVtYmVySWQiOjI0MDQwMTgzNX0.4sqgjgXe2-X75SA3N3ZfHEhTHbBkBv-tk16AmDyrTlI

### 수요조사 상세 조회
GET http://localhost:8080/surveys/1
Authorization: BEARER eyJkYXRlIjoxNzE1MTY1NzY0ODQ5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA0MDE4MzUiLCJyb2xlIjoiQURNSU4iLCJpbWFnZVVybCI6IjEiLCJuYW1lIjoi6rmA7KeA7ZmYIiwibWVtYmVyU3RhdHVzIjoi7J6s7KeBIiwiZXhwIjoxNzE1MjUyMTY0LCJkZXBhcnROYW1lIjoi7J247IKs7YyAIiwibWVtYmVySWQiOjI0MDQwMTgzNX0.4sqgjgXe2-X75SA3N3ZfHEhTHbBkBv-tk16AmDyrTlI

### 수요조사 등록
POST http://localhost:8080/surveys
Content-Type: application/json
Authorization: BEARER eyJkYXRlIjoxNzE1MTY1NzY0ODQ5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA0MDE4MzUiLCJyb2xlIjoiQURNSU4iLCJpbWFnZVVybCI6IjEiLCJuYW1lIjoi6rmA7KeA7ZmYIiwibWVtYmVyU3RhdHVzIjoi7J6s7KeBIiwiZXhwIjoxNzE1MjUyMTY0LCJkZXBhcnROYW1lIjoi7J247IKs7YyAIiwibWVtYmVySWQiOjI0MDQwMTgzNX0.4sqgjgXe2-X75SA3N3ZfHEhTHbBkBv-tk16AmDyrTlI

{
  "surveyDTO": {
    "surveyTitle": "치과예약이 있어",
    "surveyApplyDate": "2024-05-02",
    "surveyStartDate": [2024, 5, 1],
    "surveyEndDate": [2024, 5, 2]
  },
  "answers": ["답변1", "답변2", "답변3"]
}

### 수요조사 삭제
DELETE http://localhost:8080/surveys/19
Authorization: BEARER eyJkYXRlIjoxNzE1MTY1NzY0ODQ5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA0MDE4MzUiLCJyb2xlIjoiQURNSU4iLCJpbWFnZVVybCI6IjEiLCJuYW1lIjoi6rmA7KeA7ZmYIiwibWVtYmVyU3RhdHVzIjoi7J6s7KeBIiwiZXhwIjoxNzE1MjUyMTY0LCJkZXBhcnROYW1lIjoi7J247IKs7YyAIiwibWVtYmVySWQiOjI0MDQwMTgzNX0.4sqgjgXe2-X75SA3N3ZfHEhTHbBkBv-tk16AmDyrTlI

### 수요조사 응답 등록
POST http://localhost:8080/surveyResponses?surveyAnswerNo=10
Authorization: BEARER eyJkYXRlIjoxNzE1MTY1NzY0ODQ5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA0MDE4MzUiLCJyb2xlIjoiQURNSU4iLCJpbWFnZVVybCI6IjEiLCJuYW1lIjoi6rmA7KeA7ZmYIiwibWVtYmVyU3RhdHVzIjoi7J6s7KeBIiwiZXhwIjoxNzE1MjUyMTY0LCJkZXBhcnROYW1lIjoi7J247IKs7YyAIiwibWVtYmVySWQiOjI0MDQwMTgzNX0.4sqgjgXe2-X75SA3N3ZfHEhTHbBkBv-tk16AmDyrTlI
