### 회원 가입 (김지환)
POST http://localhost:8080/regist
Content-Type: application/json
Accept: */*

{
  "department": {
    "departNo": 1,
    "departName": "인사팀"
  },
  "address": "중구",
  "email": "1111111111@naver.com",
  "name": "앙리",
  "password": "0000",
  "position": {
    "positionName": "알바",
    "positionLevel": "90"
  },
  "phoneNo": "01012341234",
  "role": "ADMIN",
  "image": {
    "memberImageNo": 1,
    "memberImagePath": "이미지가 들어갈 경로"
  }
}

### 로그인 (김지환)
POST http://localhost:8080/login
Content-Type: application/json
Accept: */*

{
  "id": 240401568,
  "pass": "0000"
}

### POST 부서등록 인사팀
POST http://localhost:8080/registDepart
Content-Type: application/json
Accept: */*

{
  "departName": "관리팀"
}

### POST 직급등록 계약직
POST http://localhost:8080/registPosition
Content-Type: application/json
Accept: */*

{
  "positionName": "계약직",
  "positionLevel": "5"
}







### GET 요청 test
GET http://localhost:8080/test
Authorization: BEARER eyJkYXRlIjoxNzE0NDA5NzMyMzQzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJSb2xlIjoiQURNSU4iLCJpbWFnZSI6IuydtOuvuOyngOqwgCDrk6TslrTqsIgg6rK966GcIiwic3ViIjoiaW5zaWRlcidzIHRva2VuOiAyNDA0MDE1NjgiLCJ1c2VyTmFtZSI6Iuq5gOyngO2ZmCIsImV4cCI6MTcxNDQ5NjEzMiwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA0MDE1Njh9.rnKxgTrDvGTeRV_m_fS_WkN3bsBQiulgHpFAqP7Mul0

### POST 요청 test
POST http://localhost:8080/test
Content-Type: application/json
Accept: */*
Authorization: BEARER eyJkYXRlIjoxNzE0NDA5NzMyMzQzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJSb2xlIjoiQURNSU4iLCJpbWFnZSI6IuydtOuvuOyngOqwgCDrk6TslrTqsIgg6rK966GcIiwic3ViIjoiaW5zaWRlcidzIHRva2VuOiAyNDA0MDE1NjgiLCJ1c2VyTmFtZSI6Iuq5gOyngO2ZmCIsImV4cCI6MTcxNDQ5NjEzMiwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA0MDE1Njh9.rnKxgTrDvGTeRV_m_fS_WkN3bsBQiulgHpFAqP7Mul0

### Get 요청 회원 정보 가져오기
GET http://localhost:8080/getMemberInfo
Content-Type: application/json
Authorization: BEARER eyJkYXRlIjoxNzE0NDA5NzMyMzQzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJSb2xlIjoiQURNSU4iLCJpbWFnZSI6IuydtOuvuOyngOqwgCDrk6TslrTqsIgg6rK966GcIiwic3ViIjoiaW5zaWRlcidzIHRva2VuOiAyNDA0MDE1NjgiLCJ1c2VyTmFtZSI6Iuq5gOyngO2ZmCIsImV4cCI6MTcxNDQ5NjEzMiwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA0MDE1Njh9.rnKxgTrDvGTeRV_m_fS_WkN3bsBQiulgHpFAqP7Mul0

### GET token 김지환
GET http://localhost:8080/getToken
Content-Type: application/json
Authorization: BEARER eyJkYXRlIjoxNzE0NDA5NzMyMzQzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJSb2xlIjoiQURNSU4iLCJpbWFnZSI6IuydtOuvuOyngOqwgCDrk6TslrTqsIgg6rK966GcIiwic3ViIjoiaW5zaWRlcidzIHRva2VuOiAyNDA0MDE1NjgiLCJ1c2VyTmFtZSI6Iuq5gOyngO2ZmCIsImV4cCI6MTcxNDQ5NjEzMiwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA0MDE1Njh9.rnKxgTrDvGTeRV_m_fS_WkN3bsBQiulgHpFAqP7Mul0

### POST password 김지환
POST http://localhost:8080/updatePassword
Content-Type: application/json
Authorization: BEARER eyJkYXRlIjoxNzE0NDA5NzMyMzQzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJSb2xlIjoiQURNSU4iLCJpbWFnZSI6IuydtOuvuOyngOqwgCDrk6TslrTqsIgg6rK966GcIiwic3ViIjoiaW5zaWRlcidzIHRva2VuOiAyNDA0MDE1NjgiLCJ1c2VyTmFtZSI6Iuq5gOyngO2ZmCIsImV4cCI6MTcxNDQ5NjEzMiwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA0MDE1Njh9.rnKxgTrDvGTeRV_m_fS_WkN3bsBQiulgHpFAqP7Mul0

{
  "currentPassword": "0000",
  "newPassword123": "123123",
  "newPassword123123": "12333"
}