###
POST http://localhost:8080/api/rooms/
Content-Type: application/json

{
  "name": "민섭의 방"
}

### 방 전체 조회
GET http://localhost:8080/wss/chatting
Authorization: BEARER eyJkYXRlIjoxNzE1MDQzNTExMjUzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA1MDExMzkiLCJyb2xlIjoiQURNSU4iLCJpbWFnZVVybCI6IuydtOuvuOyngCDqsr3roZzrk6TslrTqsIgg6rOzISEhISEhIiwibmFtZSI6Iuq5gOyngO2ZmOydtOydtOydtOydtOydtOydtOOFoyIsIm1lbWJlclN0YXR1cyI6IuyerOyngSIsImV4cCI6MTcxNTEyOTkxMSwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA1MDExMzl9.G6W7UfVh2PrF3oiQyuKPx3CNUOcPPbLbR_YvPFxin0M


### 방 생성
POST http://localhost:8080/api/rooms/
Content-Type: application/json
Authorization: BEARER eyJkYXRlIjoxNzE2ODEwMDQ0ODA4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLrjIDrpqwiLCJzdWIiOiIyNDA1MDE4NDciLCJkZXBhcnRObyI6MSwicm9sZSI6IkFETUlOIiwiaW1hZ2VVcmwiOiIyNDA1MDE4NDdfamphbmcucG5nIiwibmFtZSI6Iuq5gOynseq1rCIsIm1lbWJlclN0YXR1cyI6IuyerOyngSIsImV4cCI6MTcxNjg5NjQ0NCwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA1MDE4NDd9.vdnwrLcTc5QGXzuDi6A45RuYrbwo8s7H_U79L9jsIsk

{
  "roomName": "테스트 중",
  "memberId": 202401004,
  "receiverMember" : 240502382,
  "roomStatus" : "ENTER",
  "receiverDeleteYn": "N",
  "senderDeleteYn": "N"
}

### 방 삭제 (수정)
PUT http://localhost:8080/api/rooms/2?memberId=240501847&action=delete
Authorization: BEARER eyJkYXRlIjoxNzE2ODEwMDQ0ODA4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLrjIDrpqwiLCJzdWIiOiIyNDA1MDE4NDciLCJkZXBhcnRObyI6MSwicm9sZSI6IkFETUlOIiwiaW1hZ2VVcmwiOiIyNDA1MDE4NDdfamphbmcucG5nIiwibmFtZSI6Iuq5gOynseq1rCIsIm1lbWJlclN0YXR1cyI6IuyerOyngSIsImV4cCI6MTcxNjg5NjQ0NCwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA1MDE4NDd9.vdnwrLcTc5QGXzuDi6A45RuYrbwo8s7H_U79L9jsIsk
Content-Type: application/json

### 방 조회
GET http://localhost:8080/api/rooms/?memberId=240501847&receiverMemberId=240502382
Authorization: BEARER eyJkYXRlIjoxNzE2ODEwMDQ0ODA4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLrjIDrpqwiLCJzdWIiOiIyNDA1MDE4NDciLCJkZXBhcnRObyI6MSwicm9sZSI6IkFETUlOIiwiaW1hZ2VVcmwiOiIyNDA1MDE4NDdfamphbmcucG5nIiwibmFtZSI6Iuq5gOynseq1rCIsIm1lbWJlclN0YXR1cyI6IuyerOyngSIsImV4cCI6MTcxNjg5NjQ0NCwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA1MDE4NDd9.vdnwrLcTc5QGXzuDi6A45RuYrbwo8s7H_U79L9jsIsk
Content-Type: application/json

### 방 삭제
DELETE http://localhost:8080/api/rooms/12
Content-Type: application/json
Authorization: BEARER eyJkYXRlIjoxNzE2MTY3OTAzMDE2LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA0MDEwMDEiLCJkZXBhcnRObyI6MSwicm9sZSI6IkFETUlOIiwiaW1hZ2VVcmwiOiIxIiwibmFtZSI6Iuq5gOyngO2ZmCIsIm1lbWJlclN0YXR1cyI6IuyerOyngSIsImV4cCI6MTcxNjI1NDMwMywiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA0MDEwMDF9.nqLQO0nHjmslwrSRN3EmG9qTDoKQE3UzTAdoSPWjQrA

### ??
GET http://localhost:8080/insites/leaves/240501847
Authorization: Bearer eyJkYXRlIjoxNzE2NDMzOTkwNzYzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLrjIDrpqwiLCJzdWIiOiIyNDA1MDE4NDciLCJkZXBhcnRObyI6MSwicm9sZSI6IkFETUlOIiwiaW1hZ2VVcmwiOiIyNDA1MDE4NDdfamphbmcucG5nIiwibmFtZSI6Iuq5gOynseq1rCIsIm1lbWJlclN0YXR1cyI6IuyerOyngSIsImV4cCI6MTcxNjUyMDM5MCwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA1MDE4NDd9.NP9bfIBz8_3HhAIiuDwyOWdVQkvm6ulEaoNABrPQDWk

### 메시지 저장
POST http://localhost:8080/api/messages
Content-Type: application/json
Authorization: BEARER eyJkYXRlIjoxNzE2NzEyODUwODQ5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLrjIDrpqwiLCJzdWIiOiIyNDA1MDE4NDciLCJkZXBhcnRObyI6MSwicm9sZSI6IkFETUlOIiwiaW1hZ2VVcmwiOiIyNDA1MDE4NDdfamphbmcucG5nIiwibmFtZSI6Iuq5gOynseq1rCIsIm1lbWJlclN0YXR1cyI6IuyerOyngSIsImV4cCI6MTcxNjc5OTI1MCwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA1MDE4NDd9.JZhaXpPdLjio1kQsEkFH-S_ydgSRDyAGsAas9OUztX8

{
  "enteredRoomId": 74,
  "senderId": 240501847,
  "senderName" : "김짱구",
  "message" : "ㅎㅇ"
}

### 메시지 불러오기
GET http://localhost:8080/api/messages/74
Authorization: BEARER eyJkYXRlIjoxNzE2NzEyODUwODQ5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLrjIDrpqwiLCJzdWIiOiIyNDA1MDE4NDciLCJkZXBhcnRObyI6MSwicm9sZSI6IkFETUlOIiwiaW1hZ2VVcmwiOiIyNDA1MDE4NDdfamphbmcucG5nIiwibmFtZSI6Iuq5gOynseq1rCIsIm1lbWJlclN0YXR1cyI6IuyerOyngSIsImV4cCI6MTcxNjc5OTI1MCwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA1MDE4NDd9.JZhaXpPdLjio1kQsEkFH-S_ydgSRDyAGsAas9OUztX8
