
### 전자결재 회수(update)
PUT http://localhost:8080/approvals/2024-con00001
Content-Type: application/json
Authorization: BEARER eyJkYXRlIjoxNzE1MDQyNjg4NTc4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA1MDExMzkiLCJyb2xlIjoiQURNSU4iLCJpbWFnZVVybCI6IuydtOuvuOyngCDqsr3roZzrk6TslrTqsIgg6rOzISEhISEhIiwibmFtZSI6Iuq5gOyngO2ZmOydtOydtOydtOydtOydtOydtOOFoyIsIm1lbWJlclN0YXR1cyI6IuyerOyngSIsImV4cCI6MTcxNTEyOTA4OCwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA1MDExMzl9.WAoAxg3y9bB_LBqZ2D9-nu-VukroP4Qn1unkIFMBXjA