## ================================ 부서 ================================
### 부서 등록 (김지환)
POST http://localhost:8080/departments
Content-Type: application/json
Authorization: BEARER eyJkYXRlIjoxNzE0NzE5MDc3OTc1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA1MDE5NTkiLCJyb2xlIjoiQURNSU4iLCJpbWFnZVVybCI6IuydtOuvuOyngCDqsr3roZzrk6TslrTqsIgg6rOzISEhISEhIiwibmFtZSI6Iuq5gOyngO2ZmOydtOydtOydtOydtOydtOydtOOFoyIsIm1lbWJlclN0YXR1cyI6IuyerOyngSIsImV4cCI6MTcxNDgwNTQ3NywiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA1MDE5NTl9.Bl5zyLbwZnb-9yfe_2pq0jElxIeyuNEC4JdMAUzUR9k

{
  "departName": "아아아"
}

### 특정 부서 조회 (김지환)
GET http://localhost:8080/getDepartByNo/20
Content-Type: application/json
Authorization: BEARER eyJkYXRlIjoxNzE2Mjc3MDE0MTczLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA0MDE4MzUiLCJkZXBhcnRObyI6MSwicm9sZSI6IkFETUlOIiwiaW1hZ2VVcmwiOiJodHRwczovL2ltYWdlcy5jdGZhc3NldHMubmV0L2g2Z29vOWd3MWhoNi8yc05adEZBV09kUDFsbVEzM1Z3Uk4zLzI0ZTk1M2I5MjBhOWNkMGZmMmUxZDU4Nzc0MmEyNDcyLzEtaW50cm8tcGhvdG8tZmluYWwuanBnP3c9MTIwMCZoPTk5MiZmbD1wcm9ncmVzc2l2ZSZxPTcwJmZtPWpwZyIsIm5hbWUiOiLquYDsp4DtmZgiLCJtZW1iZXJTdGF0dXMiOiLsnqzsp4EiLCJleHAiOjE3MTYzNjM0MTQsImRlcGFydE5hbWUiOiLsnbjsgqztjIAxMjMiLCJtZW1iZXJJZCI6MjQwNDAxODM1fQ.JseEgt7v9vJrSftGi2N70KF9sNfWv2Yguo0MzdDcuqE

{
  "departNo": "20"
}



### 부서 삭제
DELETE http://localhost:8080/departments/15
Content-Type: application/json
Authorization: BEARER eyJkYXRlIjoxNzE0NzE5MDc3OTc1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA1MDE5NTkiLCJyb2xlIjoiQURNSU4iLCJpbWFnZVVybCI6IuydtOuvuOyngCDqsr3roZzrk6TslrTqsIgg6rOzISEhISEhIiwibmFtZSI6Iuq5gOyngO2ZmOydtOydtOydtOydtOydtOydtOOFoyIsIm1lbWJlclN0YXR1cyI6IuyerOyngSIsImV4cCI6MTcxNDgwNTQ3NywiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA1MDE5NTl9.Bl5zyLbwZnb-9yfe_2pq0jElxIeyuNEC4JdMAUzUR9k

### 부서 수정
PUT http://localhost:8080/departments/13
Content-Type: application/json
Authorization: BEARER eyJkYXRlIjoxNzE0NzE5NTY0MTQ4LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA1MDE5NTkiLCJyb2xlIjoiQURNSU4iLCJpbWFnZVVybCI6IuydtOuvuOyngCDqsr3roZzrk6TslrTqsIgg6rOzISEhISEhIiwibmFtZSI6Iuq5gOyngO2ZmOydtOydtOydtOydtOydtOydtOOFoyIsIm1lbWJlclN0YXR1cyI6IuyerOyngSIsImV4cCI6MTcxNDgwNTk2NCwiZGVwYXJ0TmFtZSI6IuyduOyCrO2MgCIsIm1lbWJlcklkIjoyNDA1MDE5NTl9.SdZZb19LJAPBJu5WYf_0iZEfbb6wy6Gga0M5Naj6pVM

{
  "departName": "YOLOOOO"
}

### 부서 list 받기
GET http://localhost:8080/departmentDetails
Content-Type: application/json
Authorization: BEARER eyJkYXRlIjoxNzE2Mjc3MDE0MTczLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLslYzrsJQiLCJzdWIiOiIyNDA0MDE4MzUiLCJkZXBhcnRObyI6MSwicm9sZSI6IkFETUlOIiwiaW1hZ2VVcmwiOiJodHRwczovL2ltYWdlcy5jdGZhc3NldHMubmV0L2g2Z29vOWd3MWhoNi8yc05adEZBV09kUDFsbVEzM1Z3Uk4zLzI0ZTk1M2I5MjBhOWNkMGZmMmUxZDU4Nzc0MmEyNDcyLzEtaW50cm8tcGhvdG8tZmluYWwuanBnP3c9MTIwMCZoPTk5MiZmbD1wcm9ncmVzc2l2ZSZxPTcwJmZtPWpwZyIsIm5hbWUiOiLquYDsp4DtmZgiLCJtZW1iZXJTdGF0dXMiOiLsnqzsp4EiLCJleHAiOjE3MTYzNjM0MTQsImRlcGFydE5hbWUiOiLsnbjsgqztjIAxMjMiLCJtZW1iZXJJZCI6MjQwNDAxODM1fQ.JseEgt7v9vJrSftGi2N70KF9sNfWv2Yguo0MzdDcuqE
